theme: jekyll-theme-slate
title: Welcome to kosibamarcin's homepage!
description: This is my first Github Page!

template: 
 ## My Projects
 ### Shahu
 Shahu is a state of the art chess simulator. It allows players to dive into incredible world of pawns, farsighted tactics and time management. 
 Thanks to recent advancements in the area of machine learning, big data and artificial intelligence, 
 gamers are able to face one of the most complex and sophisticated AI alghoritms available*. 
 All of this can be experienced in high framerates (240FPS) and crisp, colorful, two-dimensional graphics.

![Shahu screenshot](shahu-mainMenu.png)
